'use client'
'use strict'
import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
type Measurement = { id:string; measured_at:string; weight_kg:number|null; waist_cm:number|null; body_fat_pct:number|null; notes:string|null }
export default function EvolucaoPage(){
 const [rows,setRows]=useState<Measurement[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[weight,setWeight]=useState(''),[waist,setWaist]=useState(''),[bodyFat,setBodyFat]=useState(''),[notes,setNotes]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 async function load(){const c=createClient();const {data:a}=await c.auth.getUser();if(!a.user){window.location.href='/login';return}const {data,error}=await c.from('fitness_measurements').select('id,measured_at,weight_kg,waist_cm,body_fat_pct,notes').eq('user_id',a.user.id).order('measured_at',{ascending:false});if(error)setError('Não foi possível carregar a evolução. Aplique a migration do Supabase.');else setRows(data??[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');const c=createClient();const {data:a}=await c.auth.getUser();if(!a.user){window.location.href='/login';return}const n=(v:string)=>v.trim()?Number(v.replace(',','.')):null;const {error}=await c.from('fitness_measurements').insert({user_id:a.user.id,measured_at:date,weight_kg:n(weight),waist_cm:n(waist),body_fat_pct:n(bodyFat),notes:notes.trim()||null});if(error)setError(`Não foi possível guardar a medição: ${error.message}`);else{setWeight('');setWaist('');setBodyFat('');setNotes('');await load()}setSaving(false)}
 if(loading)return <main className="page-shell"><p className="muted">Carregando evolução...</p></main>
 const latest=rows[0],first=rows[rows.length-1],delta=latest?.weight_kg!=null&&first?.weight_kg!=null?latest.weight_kg-first.weight_kg:null
 return <main className="page-shell"><header className="topbar"><Link href="/dashboard" className="brand">PRETREINO</Link><Link href="/perfil-fitness">Perfil Fitness</Link></header><section className="section-heading"><div><div className="eyebrow">EVOLUÇÃO</div><h1>O que está a mudar?</h1><p className="muted">Registe medições ao longo do tempo e acompanhe a tendência real.</p></div></section><section className="stats-grid"><div className="stat-card"><span>Registos</span><strong>{rows.length}</strong></div><div className="stat-card"><span>Peso atual</span><strong>{latest?.weight_kg!=null?`${latest.weight_kg} kg`:'—'}</strong></div><div className="stat-card"><span>Variação de peso</span><strong>{delta==null?'—':`${delta>0?'+':''}${delta.toFixed(1)} kg`}</strong></div></section><form className="measurement-form" onSubmit={submit}><h2>Nova medição</h2><div className="profile-grid"><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)} required /></label><label>Peso (kg)<input inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)} /></label><label>Cintura (cm)<input inputMode="decimal" value={waist} onChange={e=>setWaist(e.target.value)} /></label><label>Gordura corporal (%)<input inputMode="decimal" value={bodyFat} onChange={e=>setBodyFat(e.target.value)} /></label><label>Notas<input value={notes} onChange={e=>setNotes(e.target.value)} /></label></div><button className="button primary" type="submit" disabled={saving}>{saving?'Guardando...':'Registar medição'}</button></form>{error&&<p className="notice error-notice">{error}</p>}<section className="history"><h2>Histórico</h2>{rows.length===0?<p className="muted">Ainda não há medições. O primeiro registo aparece aqui.</p>:<div className="history-list">{rows.map(r=><article key={r.id} className="history-row"><div><strong>{new Date(r.measured_at+'T00:00:00').toLocaleDateString('pt-PT')}</strong>{r.notes&&<p className="muted small">{r.notes}</p>}</div><div>{r.weight_kg!=null&&<span>{r.weight_kg} kg</span>}{r.waist_cm!=null&&<span>{r.waist_cm} cm cintura</span>}{r.body_fat_pct!=null&&<span>{r.body_fat_pct}% gordura</span>}</div></article>)}</div>}</section></main>
}
